<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DTBLR01LP124" name="com.TestCaseWhiteBoard.LowerToolBarFunctionalities" tests="4" failures="1" timestamp="12 Apr 2023 11:47:11 GMT" time="77.254" errors="0">
  <testcase name="InvalidUser" time="9.512" classname="com.TestCaseWhiteBoard.LowerToolBarFunctionalities">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Logged in Succesfull] but found [User does not exist.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Logged in Succesfull] but found [User does not exist.]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.TestCaseWhiteBoard.LowerToolBarFunctionalities.InvalidUser(LowerToolBarFunctionalities.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- InvalidUser -->
  <testcase name="RenameBoard" time="16.634" classname="com.TestCaseWhiteBoard.LowerToolBarFunctionalities"/>
  <testcase name="Login" time="16.246" classname="com.TestCaseWhiteBoard.LowerToolBarFunctionalities"/>
  <testcase name="Pagination" time="34.862" classname="com.TestCaseWhiteBoard.LowerToolBarFunctionalities"/>
</testsuite> <!-- com.TestCaseWhiteBoard.LowerToolBarFunctionalities -->
